name: 'Jekyll Actions'
description: 'A GitHub Action to build and publish Jekyll sites to GitHub Pages for other repos'
inputs:
  jekyll_src:  
    description: 'The Jekyll website source directory'
    required: false
  dest_repo:
    description: 'destination repo'
    required: true
  dest_branch:
    description: 'destination branch'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jekyll_src }}
    - ${{ inputs.dest_repo }}
    - ${{ inputs.dest_branch }}
branding:
  icon: 'book'
  color: 'blue'
